apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-project-deploy
  labels:
    app: health-care-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care-project
  template:
    metadata:
      labels:
        app: health-care-project
    spec:
      containers:
      - name: health-care-project-container
        image: vishweshrushi/health_care_project
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: health-care-project-np-svc
  labels:
    app: health-care-project
spec:
  selector:
    app: health-care-project

  type: NodePort
  ports:
  - nodePort: 31111 
    port: 8082
    targetPort: 8082
